on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Paket listelerini güncelleme ve libtinfo5 paketini yükleme
      - name: Update package list and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo5
      
      # APK derleme adımı
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: . # directory where your main.py file rests

      # APK dosyalarını yükleme
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
          
