on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # macOS ortamı gerekli
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for iOS
        run: |
          brew install python3
          sudo pip3 install --upgrade pip
          sudo pip3 install kivy buildozer cython
        
      - name: Build iOS App
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v ios debug
          work-dir: . 

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-package
          path: ./bin/*.ipa  # iOS dosyası

