name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest  # macOS ortamı gerekli
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python environment
        run: python3 -m venv venv  # Sanal ortam oluştur
      
      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install kivy buildozer cython
          
      - name: Build iOS App
        run: |
          source venv/bin/activate  # Sanal ortamı etkinleştir
          buildozer -v ios debug  # iOS uygulamasını derle
          
      - name: Upload iOS IPA package
        uses: actions/upload-artifact@v4
        with:
          name: ios-package
          path: ./bin/*.ipa
